version: '3'
services:
  db:
    build: .
    container_name: bbs_db
    environment:
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
    - 5432:5432
